version: '2'

tasks:
  build:
    cmds:
      - go build -o dist/banala

  run:
    deps: [build]
    cmds:
      - dist/banala

  deploy:
    deps: [build]
    cmds:
      - rsync -arvz dist/* root@mail.protecmail.com:/root/dist/


