version: '2'

tasks:
  build:
    cmds:
      - go build -o dist/banisher

  run:
    deps: [build]
    cmds:
      - dist/banisher

  deploy:
    deps: [build]
    cmds:
      - rsync -arvz --exclude 'db.bdg' dist/*  root@mail.protecmail.com:/root/bin/
